# Generated by Django 4.2.1 on 2023-06-09 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('point_alloted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('csa', 'CSA'), ('csb', 'CSB'), ('csc', 'CSC'), ('csbs', 'CSBS'), ('eca', 'ECA'), ('ecb', 'ECB'), ('eee', 'EEE'), ('ebe', 'EBE'), ('mech', 'MECH')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_point_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.activitypoint')),
            ],
        ),
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_scored', models.IntegerField(default=0)),
                ('class_detail', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='user_api.classdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.branch')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.certificate')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.graduationyear')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.status')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classdetail',
            name='grad_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.graduationyear'),
        ),
        migrations.AddField(
            model_name='classdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_approval_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.status'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
