# Generated by Django 4.2.1 on 2023-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='registration_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
