# Generated by Django 4.1.7 on 2023-06-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='uploaded_file',
            field=models.FileField(default=None, null=True, upload_to='certificates/'),
        ),
    ]
