# Generated by Django 4.2.1 on 2023-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_certificate_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypoint',
            name='Level',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('N/A', 'N/A')], max_length=25),
        ),
    ]
