# Generated by Django 4.2.1 on 2023-06-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_activitypoint_branch_certificate_classdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.classdetail'),
        ),
    ]
