# Generated by Django 4.2.1 on 2023-06-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='registration_number',
        ),
    ]
